package com.example.birdstrace

import com.example.birdstrace.model.Taxon
import com.example.birdstrace.network.TaxRefStatut
import com.example.birdstrace.store.TaxRefCache
import com.example.birdstrace.store.TaxRefEntry

// Extrait de TaxRef v18 (PatriNat/MNHN) — oiseaux de France métropolitaine
object TaxRefLocal {

    private val noms: Map<String, Int> = mapOf(
        "accenteur alpin" to 3984,
        "accenteur mouchet" to 3978,
        "agrobate roux" to 3996,
        "aigle botte" to 2651,
        "aigle criard" to 836346,
        "aigle de bonelli" to 2657,
        "aigle des steppes" to 2648,
        "iberique" to 2634,
        "aigle imperial" to 2643,
        "aigle pomarin" to 836345,
        "aigle royal" to 2645,
        "aigrette des recifs" to 2494,
        "aigrette garzette" to 2497,
        "alouette calandre" to 3644,
        "alouette calandrelle" to 3649,
        "alouette des champs" to 3676,
        "alouette haussecol" to 3681,
        "alouette lulu" to 3670,
        "alouette monticole" to 3646,
        "alouette pispolette" to 885382,
        "ammomane elegante" to 886215,
        "autour des palombes" to 2891,
        "avocette elegante" to 3116,
        "balbuzard pecheur" to 2660,
        "barge rousse" to 2568,
        "barge a queue noire" to 2563,
        "bartramie des champs" to 199360,
        "bec-croise bifascie" to 4609,
        "bec-croise des sapins" to 4603,
        "bec-croise perroquet" to 4607,
        "becasse d'amerique" to 199351,
        "becasse des bois" to 2560,
        "becasseau a cou roux" to 2636,
        "becasseau a echasses" to 199348,
        "becasseau a longs doigts" to 2540,
        "becasseau a queue pointue" to 2551,
        "becasseau cocorli" to 2533,
        "becasseau d'alaska" to 199349,
        "becasseau de baird" to 199341,
        "becasseau de temminck" to 2538,
        "becasseau falcinelle" to 2543,
        "becasseau maubech" to 2530,
        "becasseau minute" to 2536,
        "becasseau sanderling" to 2527,
        "becasseau variable" to 2535,
        "becasseau violet" to 2532,
        "becassin a bec court" to 199353,
        "becassin a long bec" to 199354,
        "becassine des marais" to 2557,
        "becassine double" to 2555,
        "becassine sourde" to 2553,
        "bergeronnette citrine" to 3948,
        "bergeronnette des ruisseaux" to 3755,
        "bergeronnette grise" to 3941,
        "bergeronnette orientale" to 962840,
        "bergeronnette printaniere" to 3741,
        "bernache cravant" to 2757,
        "bernache du canada" to 2747,
        "bernache nonnette" to 2750,
        "bernache a cou roux" to 2753,
        "bihoreau gris" to 2481,
        "blongios nain" to 2477,
        "bondree apivore" to 2832,
        "bouscarle de cetti" to 4151,
        "bouvreuil pivoine" to 4619,
        "bruant aureole" to 4678,
        "bruant cendrillard" to 4674,
        "bruant des neiges" to 4649,
        "bruant des roseaux" to 4669,
        "bruant fou" to 4663,
        "bruant jaune" to 4659,
        "bruant lapon" to 4645,
        "bruant masque" to 4665,
        "bruant melanocephale" to 4675,
        "bruant nain" to 4667,
        "bruant ortolan" to 4661,
        "bruant proyer" to 4671,
        "bruant roux" to 4676,
        "bruant rustique" to 4657,
        "bruant zizi" to 4655,
        "bruant a calotte blanche" to 199510,
        "bruant a couronne blanche" to 199511,
        "bruant a gorge blanche" to 199512,
        "bruant a sourcils jaunes" to 4651,
        "bruant a tete rousse" to 4677,
        "busard cendr" to 2920,
        "busard des roseaux" to 2907,
        "busard pale" to 2916,
        "busard saint-martin" to 2910,
        "buse feroe" to 2966,
        "buse pattue" to 2963,
        "buse variable" to 2947,
        "butor etoile" to 2470,
        "caille des bles" to 2864,
        "canard chipeau" to 2805,
        "canard colvert" to 2815,
        "canard mandarin" to 2803,
        "canard noir" to 2825,
        "canard pilet" to 2811,
        "canard siffleur" to 2797,
        "canard souchet" to 2808,
        "canard a front blanc" to 199207,
        "cassenoix mouchete" to 3449,
        "chardonneret elegant" to 4580,
        "chevalier aboyeur" to 2600,
        "chevalier arlequin" to 2616,
        "chevalier bargette" to 2610,
        "chevalier criard" to 2597,
        "chevalier culblanc" to 2607,
        "chevalier de siberie" to 199368,
        "chevalier gambette" to 2594,
        "chevalier grivele" to 199367,
        "chevalier guignette" to 2604,
        "chevalier stagnatile" to 2603,
        "chevalier sylvain" to 2609,
        "chevech d'athena" to 3352,
        "chevechette d'europe" to 3350,
        "chocard a bec jaune" to 3432,
        "choucas des tours" to 3444,
        "chouette de tengmalm" to 3345,
        "chouette epervier" to 3362,
        "chouette hulotte" to 3340,
        "cigogne blanche" to 2463,
        "cigogne noire" to 2461,
        "cincle plongeur" to 3971,
        "circaete jean-le-blanc" to 2835,
        "cisticole des joncs" to 4145,
        "cochevis de thekla" to 3685,
        "cochevis huppe" to 3683,
        "combattant varie" to 2545,
        "corbeau freux" to 3451,
        "cormoran huppe" to 2465,
        "cormoran pygmee" to 2473,
        "corneille mantelee" to 3457,
        "corneille noire" to 3454,
        "coucou geai" to 3287,
        "coucou gris" to 3290,
        "coulicou a bec jaune" to 199400,
        "coulicou a bec noir" to 199401,
        "courlis a bec grele" to 2575,
        "courlis cendre" to 2571,
        "courlis corlieu" to 2573,
        "courvite isabelle" to 2505,
        "crabier chevelu" to 2483,
        "crave a bec rouge" to 3434,
        "cygne chanteur" to 2760,
        "cygne de bewick" to 2762,
        "cygne noir" to 933316,
        "cygne tuberculé" to 2765,
        "durbec des sapins" to 4616,
        "echasse blanche" to 3119,
        "effraie des clochers" to 3302,
        "eider a duvet" to 2782,
        "elanion blanc" to 2838,
        "engoulevent d'europe" to 3218,
        "epervier d'europe" to 2887,
        "erismaturer rousse" to 2795,
        "etoumeau sansonnet" to 3526,
        "etourneau sansonnet" to 3526,
        "etourneau roselin" to 3524,
        "etourneau unicolore" to 3528,
        "faisan de colchide" to 2875,
        "faucon concolore" to 3012,
        "faucon crecerelle" to 3021,
        "faucon crecerellette" to 3019,
        "faucon d'eleonore" to 3015,
        "faucon emerillon" to 3027,
        "faucon gerfaut" to 3006,
        "faucon hobereau" to 3024,
        "faucon kobez" to 3030,
        "faucon lanier" to 3009,
        "faucon pelerin" to 3032,
        "faucon sacre" to 3008,
        "fauvette a lunettes" to 4096,
        "fauvette a tete noire" to 4094,
        "fauvette babillarde" to 4083,
        "fauvette des jardins" to 4085,
        "fauvette epervier" to 4067,
        "fauvette grisette" to 4081,
        "fauvette melanocephale" to 4090,
        "fauvette naine" to 4073,
        "fauvette orphee" to 4078,
        "fauvette passerinette" to 4074,
        "fauvette pitchou" to 4065,
        "fauvette sarde" to 4069,
        "flamant rose" to 2468,
        "fou de bassan" to 2467,
        "foulque macroule" to 2876,
        "fuligule a bec cercle" to 2776,
        "fuligule milouin" to 2769,
        "fuligule milouinan" to 2771,
        "fuligule morillon" to 2773,
        "fuligule nyroca" to 2776,
        "fulmar boreal" to 2413,
        "gallinule poule-d'eau" to 2869,
        "garrot a oeil d'or" to 2779,
        "geai des chenes" to 3437,
        "gelinotte des bois" to 2855,
        "glareole a collier" to 2507,
        "gobemouche a collier" to 4037,
        "gobemouche gris" to 4039,
        "gobemouche noir" to 4035,
        "goeland argente" to 2374,
        "goeland bourgmestre" to 2370,
        "goeland brun" to 2377,
        "goeland cendre" to 2379,
        "goeland d'audouin" to 2385,
        "goeland leucophee" to 2388,
        "goeland marin" to 2371,
        "goeland railleur" to 2392,
        "goglu des pres" to 4694,
        "gorgebleue a miroir" to 3849,
        "grand corbeau" to 3460,
        "grand cormoran" to 2469,
        "grand gravelot" to 3070,
        "grand labbe" to 2322,
        "grand tetras" to 2851,
        "grand-duc d'europe" to 3305,
        "grande aigrette" to 2499,
        "grebe a cou noir" to 2407,
        "grebe castagneux" to 2402,
        "grebe huppe" to 2410,
        "grebe jougris" to 2405,
        "grimpereau des bois" to 3578,
        "grimpereau des jardins" to 3580,
        "grive draine" to 3791,
        "grive litorne" to 3795,
        "grive mauvis" to 3793,
        "grive musicienne" to 3789,
        "grosbec casse-noyaux" to 4624,
        "grue cendr" to 2878,
        "guepier d'europe" to 3262,
        "guifette noire" to 2356,
        "guillemot de troil" to 2342,
        "gypaete barbu" to 2845,
        "harelde boreale" to 2784,
        "harfang des neiges" to 3307,
        "harle bievre" to 2793,
        "harle huppe" to 2791,
        "harle piette" to 2789,
        "heron cendre" to 2490,
        "heron garde-boeufs" to 2501,
        "heron pourpre" to 2493,
        "hibou des marais" to 3333,
        "hibou moyen-duc" to 3330,
        "hirondelle de fenetre" to 3736,
        "hirondelle de rivage" to 3730,
        "hirondelle de rochers" to 3738,
        "hirondelle rousseline" to 3732,
        "hirondelle rustique" to 3734,
        "huitrier pie" to 3111,
        "huppe fasciee" to 3258,
        "hypolais icterin" to 4041,
        "hypolais polyglotte" to 4044,
        "ibis falcinelle" to 2459,
        "jaseur boreal" to 3516,
        "lagopede alpin" to 2857,
        "linotte melodieuse" to 4571,
        "locustelle fasciee" to 4147,
        "locustelle fluviatile" to 4149,
        "locustelle luscinioid" to 4155,
        "locustelle tachetee" to 4153,
        "loriot d'europe" to 3423,
        "macareux moine" to 2344,
        "martin-pecheur d'europe" to 3255,
        "martinet a ventre blanc" to 3229,
        "martinet des maisons" to 3231,
        "martinet noir" to 3233,
        "martinet pale" to 3225,
        "mergule nain" to 2348,
        "merle a plastron" to 3783,
        "merle noir" to 3785,
        "mesange azuree" to 3606,
        "mesange bleue" to 3609,
        "mesange boreal" to 3601,
        "mesange charbonniere" to 3611,
        "mesange huppee" to 3596,
        "mesange noire" to 3598,
        "mesange nonnette" to 3603,
        "milan noir" to 2900,
        "milan royal" to 2903,
        "moineau cisalpin" to 4537,
        "moineau domestique" to 4525,
        "moineau espagnol" to 4527,
        "moineau friquet" to 4542,
        "moineau soulcie" to 4530,
        "monticole bleu" to 3780,
        "monticole de roche" to 3778,
        "mouette melanocephale" to 2395,
        "mouette pygmee" to 2398,
        "mouette rieuse" to 2400,
        "mouette tridactyle" to 2363,
        "nette rousse" to 2767,
        "niverolle alpine" to 4518,
        "oedicneme criard" to 2503,
        "oie a bec court" to 2733,
        "oie cendr" to 2726,
        "oie naine" to 2737,
        "oie rieuse" to 2730,
        "oriole de baltimore" to 199647,
        "orite a longue queue" to 3590,
        "ouette d'egypte" to 2743,
        "outarde barbue" to 2882,
        "outarde canepetiere" to 2884,
        "panure a moustaches" to 3593,
        "pelican blanc" to 2457,
        "perdrix bartavelle" to 2868,
        "perdrix grise" to 2866,
        "perdrix rouge" to 2862,
        "perruche a collier" to 3284,
        "petit gravelot" to 3076,
        "petit-duc scops" to 3312,
        "phalarope a bec etroit" to 2622,
        "phalarope a bec large" to 2620,
        "phragmite aquatique" to 4165,
        "phragmite des joncs" to 4161,
        "pic a dos blanc" to 3210,
        "pic cendr" to 3196,
        "pic epeiche" to 3201,
        "pic epeichette" to 3207,
        "pic mar" to 3199,
        "pic noir" to 3194,
        "pic tridactyle" to 3213,
        "pic vert" to 3190,
        "pie bavarde" to 3439,
        "pie-grieche a tete rousse" to 3406,
        "pie-grieche ecorcheur" to 3400,
        "pie-grieche grise" to 3402,
        "pie-grieche meridionale" to 3404,
        "pigeon biset" to 3237,
        "pigeon colombin" to 3239,
        "pigeon ramier" to 3241,
        "pingouin torda" to 2340,
        "pinson des arbres" to 4556,
        "pinson du nord" to 4558,
        "pipit a gorge rousse" to 3713,
        "pipit des arbres" to 3705,
        "pipit farlouse" to 3719,
        "pipit maritime" to 3727,
        "pipit rousseline" to 3701,
        "pipit spioncelle" to 3724,
        "plongeon arctique" to 2416,
        "plongeon catmarin" to 2418,
        "plongeon imbrin" to 2420,
        "pluvier argente" to 3105,
        "pluvier dore" to 3100,
        "pouillot de bonelli" to 4011,
        "pouillot fitis" to 4017,
        "pouillot siffleur" to 4013,
        "pouillot veloce" to 4015,
        "pouillot verdatre" to 4009,
        "pygargue a queue blanche" to 2841,
        "rale d'eau" to 2874,
        "rale des genets" to 2872,
        "remiz penduline" to 3618,
        "roitelet a triple bandeau" to 4060,
        "roitelet huppe" to 4062,
        "rollier d'europe" to 3260,
        "rossignol philomele" to 3851,
        "rougegorge familier" to 3855,
        "rougequeue a front blanc" to 3858,
        "rougequeue noir" to 3856,
        "rousserolle effarvatte" to 4167,
        "rousserolle turdoide" to 4171,
        "rousserolle verderolle" to 4169,
        "sarcelle d'ete" to 2818,
        "sarcelle d'hiver" to 2820,
        "sarcelle marbree" to 2822,
        "serin cini" to 4563,
        "sittelle torchepot" to 3575,
        "sizerin flamme" to 4587,
        "spatule blanche" to 2456,
        "sterne arctique" to 2335,
        "sterne caspienne" to 2328,
        "sterne caugek" to 2330,
        "sterne hansel" to 2326,
        "sterne naine" to 2337,
        "sterne pierregarin" to 2332,
        "tadorne casarca" to 2745,
        "tadorne de belon" to 2741,
        "taleve sultane" to 2877,
        "tarier des pres" to 3873,
        "tarier patre" to 3871,
        "tarin des aulnes" to 4573,
        "tetras lyre" to 2853,
        "tichodrome echelette" to 3582,
        "torcol fourmilier" to 3186,
        "tournepierre a collier" to 2618,
        "tourterelle des bois" to 3247,
        "tourterelle turque" to 3243,
        "traquet motteux" to 3820,
        "traquet oreillard" to 3829,
        "traquet pie" to 3840,
        "troglodyte mignon" to 3975,
        "vanneau huppe" to 3092,
        "vautour fauve" to 2842,
        "vautour moine" to 2846,
        "vautour percnoptere" to 2848,
        "venturon montagnard" to 4566,
        "verdier d'europe" to 4576
    )

    private val sciNoms: Map<Int, String> = mapOf(
        3984 to "Prunella collaris", 3978 to "Prunella modularis", 3996 to "Cercotrichas galactotes",
        2651 to "Hieraaetus pennatus", 2645 to "Aquila chrysaetos", 2497 to "Egretta garzetta",
        3676 to "Alauda arvensis", 3670 to "Lullula arborea", 2891 to "Accipiter gentilis",
        3116 to "Recurvirostra avosetta", 2660 to "Pandion haliaetus", 2563 to "Limosa limosa",
        2568 to "Limosa lapponica", 2560 to "Scolopax rusticola", 4609 to "Loxia leucoptera",
        4603 to "Loxia curvirostra", 4607 to "Loxia pytyopsittacus", 3948 to "Motacilla citreola",
        3755 to "Motacilla cinerea", 3941 to "Motacilla alba", 3741 to "Motacilla flava",
        2757 to "Branta bernicla", 2747 to "Branta canadensis", 2750 to "Branta leucopsis",
        2481 to "Nycticorax nycticorax", 2477 to "Ixobrychus minutus", 2832 to "Pernis apivorus",
        4151 to "Cettia cetti", 4619 to "Pyrrhula pyrrhula", 4659 to "Emberiza citrinella",
        4669 to "Emberiza schoeniclus", 4663 to "Emberiza cia", 4661 to "Emberiza hortulana",
        4671 to "Miliaria calandra", 4655 to "Emberiza cirlus", 2920 to "Circus pygargus",
        2907 to "Circus aeruginosus", 2910 to "Circus cyaneus", 2947 to "Buteo buteo",
        2963 to "Buteo lagopus", 2470 to "Botaurus stellaris", 2864 to "Coturnix coturnix",
        2805 to "Anas strepera", 2815 to "Anas platyrhynchos", 2811 to "Anas acuta",
        2797 to "Anas penelope", 2808 to "Anas clypeata", 4580 to "Carduelis carduelis",
        2600 to "Tringa nebularia", 2594 to "Tringa totanus", 2604 to "Actitis hypoleucos",
        3352 to "Athene noctua", 3305 to "Bubo bubo", 3340 to "Strix aluco",
        3432 to "Pyrrhocorax graculus", 3444 to "Corvus monedula", 3345 to "Aegolius funereus",
        2463 to "Ciconia ciconia", 2461 to "Ciconia nigra", 3971 to "Cinclus cinclus",
        2835 to "Circaetus gallicus", 4145 to "Cisticola juncidis", 3685 to "Galerida theklae",
        3683 to "Galerida cristata", 3451 to "Corvus frugilegus", 2465 to "Phalacrocorax aristotelis",
        3454 to "Corvus corone", 3457 to "Corvus cornix", 3287 to "Clamator glandarius",
        3290 to "Cuculus canorus", 2575 to "Numenius tenuirostris", 2571 to "Numenius arquata",
        2573 to "Numenius phaeopus", 3119 to "Himantopus himantopus", 3302 to "Tyto alba",
        2782 to "Somateria mollissima", 2838 to "Elanus caeruleus", 3218 to "Caprimulgus europaeus",
        2887 to "Accipiter nisus", 3526 to "Sturnus vulgaris", 3524 to "Sturnus roseus",
        2875 to "Phasianus colchicus", 3021 to "Falco tinnunculus", 3019 to "Falco naumanni",
        3027 to "Falco columbarius", 3006 to "Falco rusticolus", 3024 to "Falco subbuteo",
        3032 to "Falco peregrinus", 3009 to "Falco biarmicus", 3008 to "Falco cherrug",
        4094 to "Sylvia atricapilla", 4083 to "Sylvia curruca", 4085 to "Sylvia borin",
        4081 to "Sylvia communis", 4090 to "Sylvia melanocephala", 4065 to "Sylvia undata",
        2468 to "Phoenicopterus roseus", 2467 to "Morus bassanus", 2876 to "Fulica atra",
        2769 to "Aythya ferina", 2773 to "Aythya fuligula", 2413 to "Fulmarus glacialis",
        2869 to "Gallinula chloropus", 2779 to "Bucephala clangula", 3437 to "Garrulus glandarius",
        2855 to "Bonasa bonasia", 3437 to "Garrulus glandarius", 2855 to "Bonasa bonasia",
        4037 to "Ficedula albicollis", 4039 to "Muscicapa striata", 4035 to "Ficedula hypoleuca",
        2374 to "Larus argentatus", 2370 to "Larus hyperboreus", 2377 to "Larus fuscus",
        2379 to "Larus canus", 2385 to "Larus audouinii", 2388 to "Larus michahellis",
        2371 to "Larus marinus", 3849 to "Luscinia svecica", 3460 to "Corvus corax",
        2469 to "Phalacrocorax carbo", 3070 to "Charadrius hiaticula", 2322 to "Catharacta skua",
        2851 to "Tetrao urogallus", 2499 to "Ardea alba", 2407 to "Podiceps nigricollis",
        2402 to "Tachybaptus ruficollis", 2410 to "Podiceps cristatus", 3578 to "Certhia familiaris",
        3580 to "Certhia brachydactyla", 3791 to "Turdus viscivorus", 3795 to "Turdus pilaris",
        3793 to "Turdus iliacus", 3789 to "Turdus philomelos", 4624 to "Coccothraustes coccothraustes",
        2878 to "Grus grus", 3262 to "Merops apiaster", 2356 to "Chlidonias niger",
        2342 to "Alca torda", 2845 to "Gypaetus barbatus", 2784 to "Clangula hyemalis",
        3307 to "Bubo scandiacus", 2793 to "Mergus merganser", 2791 to "Mergus serrator",
        2789 to "Mergus albellus", 2490 to "Ardea cinerea", 2501 to "Bubulcus ibis",
        2493 to "Ardea purpurea", 3333 to "Asio flammeus", 3330 to "Asio otus",
        3736 to "Delichon urbicum", 3730 to "Riparia riparia", 3738 to "Ptyonoprogne rupestris",
        3732 to "Cecropis daurica", 3734 to "Hirundo rustica", 3111 to "Haematopus ostralegus",
        3258 to "Upupa epops", 4041 to "Hippolais icterina", 4044 to "Hippolais polyglotta",
        2459 to "Plegadis falcinellus", 3516 to "Bombycilla garrulus", 3618 to "Remiz pendulinus",
        4060 to "Regulus ignicapilla", 4062 to "Regulus regulus", 3260 to "Coracias garrulus",
        3851 to "Luscinia megarhynchos", 3855 to "Erithacus rubecula", 3858 to "Phoenicurus phoenicurus",
        3856 to "Phoenicurus ochruros", 4167 to "Acrocephalus scirpaceus", 4171 to "Acrocephalus arundinaceus",
        4169 to "Acrocephalus palustris", 2818 to "Anas querquedula", 2820 to "Anas crecca",
        4563 to "Serinus serinus", 3575 to "Sitta europaea", 4587 to "Carduelis flammea",
        2456 to "Platalea leucorodia", 2335 to "Sterna paradisaea", 2328 to "Hydroprogne caspia",
        2332 to "Sterna hirundo", 2337 to "Sternula albifrons", 2745 to "Tadorna ferruginea",
        2741 to "Tadorna tadorna", 3873 to "Saxicola rubetra", 3871 to "Saxicola torquatus",
        4573 to "Carduelis spinus", 2853 to "Tetrao tetrix", 3582 to "Tichodroma muraria",
        3186 to "Jynx torquilla", 2618 to "Arenaria interpres", 3247 to "Streptopelia turtur",
        3243 to "Streptopelia decaocto", 3820 to "Oenanthe oenanthe", 3829 to "Oenanthe hispanica",
        3975 to "Troglodytes troglodytes", 3092 to "Vanellus vanellus", 2842 to "Gyps fulvus",
        2846 to "Aegypius monachus", 4576 to "Chloris chloris", 3312 to "Otus scops",
        2874 to "Rallus aquaticus", 2872 to "Crex crex", 2841 to "Haliaeetus albicilla",
        4566 to "Serinus citrinella", 4558 to "Fringilla montifringilla", 4556 to "Fringilla coelebs",
        4525 to "Passer domesticus", 4542 to "Passer montanus", 3780 to "Monticola solitarius",
        3778 to "Monticola saxatilis", 3596 to "Lophophanes cristatus", 3598 to "Periparus ater",
        3601 to "Poecile montanus", 3603 to "Poecile palustris", 3606 to "Cyanistes cyanus",
        3609 to "Cyanistes caeruleus", 3611 to "Parus major", 2900 to "Milvus migrans",
        2903 to "Milvus milvus", 4537 to "Passer italiae", 4530 to "Petronia petronia",
        2503 to "Burhinus oedicnemus", 2726 to "Anser anser", 2730 to "Anser albifrons",
        2737 to "Anser erythropus", 3590 to "Aegithalos caudatus", 2743 to "Alopochen aegyptiaca",
        2882 to "Otis tarda", 2884 to "Tetrax tetrax", 3593 to "Panurus biarmicus",
        2457 to "Pelecanus onocrotalus", 2868 to "Alectoris graeca", 2866 to "Perdix perdix",
        2862 to "Alectoris rufa", 3284 to "Psittacula krameri", 3076 to "Charadrius dubius",
        2622 to "Phalaropus lobatus", 2620 to "Phalaropus fulicarius", 4165 to "Acrocephalus paludicola",
        4161 to "Acrocephalus schoenobaenus", 3210 to "Dendrocopos leucotos", 3196 to "Picus canus",
        3201 to "Dendrocopos major", 3207 to "Dendrocopos minor", 3199 to "Leiopicus medius",
        3194 to "Dryocopus martius", 3213 to "Picoides tridactylus", 3190 to "Picus viridis",
        3439 to "Pica pica", 3406 to "Lanius senator", 3400 to "Lanius collurio",
        3402 to "Lanius excubitor", 3404 to "Lanius meridionalis", 3237 to "Columba livia",
        3239 to "Columba oenas", 3241 to "Columba palumbus", 2340 to "Alca torda",
        3700 to "Anthus campestris", 3705 to "Anthus trivialis", 3719 to "Anthus pratensis",
        3727 to "Anthus petrosus", 3724 to "Anthus spinoletta", 2416 to "Gavia arctica",
        2418 to "Gavia stellata", 2420 to "Gavia immer", 3105 to "Pluvialis squatarola",
        3100 to "Pluvialis apricaria", 4011 to "Phylloscopus bonelli", 4017 to "Phylloscopus trochilus",
        4013 to "Phylloscopus sibilatrix", 4015 to "Phylloscopus collybita", 4009 to "Phylloscopus trochiloides",
        3255 to "Alcedo atthis", 3229 to "Tachymarptis melba", 3231 to "Apus pallidus",
        3233 to "Apus apus", 3783 to "Turdus torquatus", 3785 to "Turdus merula",
        3701 to "Anthus campestris", 2422 to "Podiceps auritus", 2395 to "Larus melanocephalus",
        2398 to "Hydrocoloeus minutus", 2400 to "Chroicocephalus ridibundus", 2363 to "Rissa tridactyla",
        2767 to "Netta rufina", 4518 to "Montifringilla nivalis", 4571 to "Linaria cannabina",
        4149 to "Locustella fluviatilis", 4155 to "Locustella luscinioides", 4153 to "Locustella naevia",
        3423 to "Oriolus oriolus", 2348 to "Alle alle", 3225 to "Apus pallidus",
        4147 to "Locustella fasciolata", 2457 to "Pelecanus onocrotalus", 4096 to "Sylvia conspicillata",
        3644 to "Melanocorypha calandra", 3649 to "Calandrella brachydactyla", 3681 to "Eremophila alpestris",
        3646 to "Monticola saxatilis", 885382 to "Calandrella rufescens", 886215 to "Ammomanes elegans",
        3650 to "Calandrella brachydactyla"
    )

    fun getSuggestions(taxon: Taxon?): List<String> = when (taxon) {
        Taxon.MAMMIFERE -> mammiferesSuggestions
        Taxon.REPTILE   -> reptilesSuggestions
        else            -> suggestions
    }

    fun getSuggestionsAutocomplete(taxon: Taxon?, scientifique: Boolean): List<String> {
        val animalGroups = setOf("Oiseaux", "Mammifères", "Reptiles")

        // Pour Plantes : utiliser uniquement le cache (groupes non-animaux)
        if (taxon == Taxon.PLANTE) {
            val groupes = TaxRefCache.tousLesGroupes()
            val parCdNom = mutableMapOf<Int, TaxRefEntry>()
            for ((_, entry) in TaxRefCache.toutesLesEntrees()) {
                val gr = groupes[entry.cdNom.toString()]
                if (gr != null && gr !in animalGroups) parCdNom[entry.cdNom] = entry
            }
            return if (scientifique)
                parCdNom.values.map { it.sciNom }.filter { it.isNotEmpty() }.distinct().sorted()
            else
                parCdNom.values.mapNotNull { it.vernNom }.filter { it.isNotEmpty() }.distinct().sorted()
        }

        val groupeCible = when (taxon) {
            Taxon.MAMMIFERE -> "Mammifères"
            Taxon.REPTILE   -> "Reptiles"
            else            -> "Oiseaux"
        }
        // Cache GeoNature en premier : déduplication par cdNom, filtré par groupe
        val groupes = TaxRefCache.tousLesGroupes()
        if (groupes.isNotEmpty()) {
            val parCdNom = mutableMapOf<Int, TaxRefEntry>()
            for ((_, entry) in TaxRefCache.toutesLesEntrees()) {
                if (groupes[entry.cdNom.toString()] == groupeCible) {
                    parCdNom[entry.cdNom] = entry
                }
            }
            if (parCdNom.isNotEmpty()) {
                return if (scientifique) {
                    parCdNom.values.map { it.sciNom }.filter { it.isNotEmpty() }.distinct().sorted()
                } else {
                    parCdNom.values.mapNotNull { it.vernNom }.filter { it.isNotEmpty() }.distinct().sorted()
                }
            }
        }
        // Fallback : données embarquées TaxRefLocal
        return if (scientifique) {
            getSuggestions(taxon).mapNotNull { nom ->
                noms[TaxRefCache.normaliser(nom)]?.let { sciNoms[it] }
            }.distinct().sorted()
        } else {
            getSuggestions(taxon)
        }
    }

    // Mammifères de France — source : INPN / UICN
    val mammiferesSuggestions: List<String> = listOf(
        "Belette d'Europe", "Bison d'Europe", "Blaireau européen",
        "Bouquetin des Alpes", "Bouquetin ibérique",
        "Campagnol agreste", "Campagnol amphibie", "Campagnol de Fatio",
        "Campagnol des champs", "Campagnol des neiges", "Campagnol provençal",
        "Campagnol souterrain",
        "Castor d'Europe",
        "Cerf élaphe",
        "Chamois",
        "Chauve-souris de Nathusius", "Chauve-souris de Natterer",
        "Chat forestier",
        "Chevreuil européen",
        "Chien viverrin",
        "Crocidure des jardins", "Crocidure leucode", "Crocidure musette",
        "Crossope aquatique", "Crossope de Miller",
        "Daim",
        "Écureuil roux",
        "Élan",
        "Fouine",
        "Genette commune",
        "Grand dauphin", "Grand murin",
        "Grand rhinolophe",
        "Grande noctule",
        "Hérisson d'Europe",
        "Isard",
        "Lapin de garenne",
        "Lièvre brun", "Lièvre d'Italie", "Lièvre variable",
        "Loup gris",
        "Loutre d'Europe",
        "Lynx boréal",
        "Marsouin commun",
        "Martre des pins",
        "Mouflon",
        "Murin à moustaches", "Murin à oreilles échancrées", "Murin d'Alcathoe",
        "Murin de Bechstein", "Murin de Brandt", "Murin de Daubenton",
        "Musaraigne aquatique", "Musaraigne bicolore", "Musaraigne carrelet",
        "Musaraigne couronnée", "Musaraigne de Miller", "Musaraigne des Alpes",
        "Mulot à collier", "Mulot des champs", "Mulot du Caucase", "Mulot fauve",
        "Mulot ibérique", "Mulot sylvestre",
        "Muscardin",
        "Noctule commune", "Noctule de Leisler",
        "Oreillard gris", "Oreillard montagnard", "Oreillard roux",
        "Orque",
        "Ours brun",
        "Petit murin",
        "Petit rhinolophe",
        "Pipistrelle commune", "Pipistrelle de Kuhl", "Pipistrelle de Nathusius",
        "Pipistrelle pygmée", "Pipistrelle soprane",
        "Putois d'Europe",
        "Ragondin",
        "Rat brun", "Rat des moissons", "Rat musqué", "Rat noir",
        "Renard roux",
        "Rhinolophe euryale", "Rhinolophe de Méhely",
        "Sanglier",
        "Sérotine bicolore", "Sérotine commune", "Sérotine de Nilsson",
        "Sérotine isabelle",
        "Souslik d'Europe",
        "Taupe d'Europe",
        "Vison d'Amérique", "Vison d'Europe",
        "Zorille"
    )

    // Reptiles de France — source : INPN / SFEPM
    val reptilesSuggestions: List<String> = listOf(
        "Cistude d'Europe",
        "Coronelle austriaque", "Coronelle girondine",
        "Couleuvre à collier", "Couleuvre à échelons", "Couleuvre d'Esculape",
        "Couleuvre de Montpellier", "Couleuvre helvétique", "Couleuvre verte et jaune",
        "Gecko des murailles", "Gecko turc",
        "Lézard agile", "Lézard catalan", "Lézard des murailles", "Lézard des souches",
        "Lézard ocellé", "Lézard vert occidental",
        "Orvet de Vérone", "Orvet fragile",
        "Psammodrome d'Edwards", "Psammodrome hispanique",
        "Seps strié",
        "Tarente de Mauritanie",
        "Tortue de Hermann", "Tortue des steppes",
        "Vipère aspic", "Vipère d'Orsini", "Vipère péliade", "Vipère de Seoane"
    )

    fun rechercher(nom: String): TaxRefStatut {
        val cle = TaxRefCache.normaliser(nom)

        // Recherche par nom français
        noms[cle]?.let { cdNom ->
            val nomFr = suggestions.find { TaxRefCache.normaliser(it) == cle }
            return TaxRefStatut.Trouve(cdNom, sciNoms[cdNom] ?: "", nomFr)
        }

        // Recherche par nom scientifique (mode sci activé)
        val nomLc = nom.trim().lowercase()
        sciNoms.entries.firstOrNull { it.value.lowercase() == nomLc }?.let { (cdNom, sciNom) ->
            return TaxRefStatut.Trouve(cdNom, sciNom, null)
        }

        return TaxRefStatut.NonTrouve
    }

    val suggestions: List<String> = listOf(
        "Accenteur à gorge noire", "Accenteur alpin", "Accenteur mouchet",
        "Agrobate roux", "Aigle botté", "Aigle criard", "Aigle de Bonelli",
        "Aigle des steppes", "Aigle ibérique", "Aigle impérial", "Aigle pomarin", "Aigle royal",
        "Aigrette des récifs", "Aigrette garzette",
        "Alouette calandre", "Alouette calandrelle", "Alouette des champs",
        "Alouette haussecol", "Alouette lulu", "Alouette monticole", "Alouette pispolette",
        "Ammomane élégante", "Autour des palombes", "Avocette élégante",
        "Balbuzard pêcheur", "Barge à queue noire", "Barge rousse",
        "Bartramie des champs", "Bec-croisé bifascié", "Bec-croisé des sapins", "Bec-croisé perroquet",
        "Bécasse d'Amérique", "Bécasse des bois",
        "Bécasseau à cou roux", "Bécasseau à échasses", "Bécasseau à longs doigts",
        "Bécasseau à queue pointue", "Bécasseau cocorli", "Bécasseau d'Alaska",
        "Bécasseau de Baird", "Bécasseau de Temminck", "Bécasseau falcinelle",
        "Bécasseau maubèche", "Bécasseau minute", "Bécasseau sanderling",
        "Bécasseau variable", "Bécasseau violet",
        "Bécassin à bec court", "Bécassin à long bec",
        "Bécassine des marais", "Bécassine double", "Bécassine sourde",
        "Bergeronnette citrine", "Bergeronnette des ruisseaux", "Bergeronnette grise",
        "Bergeronnette orientale", "Bergeronnette printanière",
        "Bernache à cou roux", "Bernache cravant", "Bernache du Canada", "Bernache nonnette",
        "Bihoreau gris", "Blongios nain",
        "Bondrée apivore", "Bouscarle de Cetti", "Bouvreuil pivoine",
        "Bruant à calotte blanche", "Bruant à couronne blanche", "Bruant à gorge blanche",
        "Bruant à sourcils jaunes", "Bruant à tête rousse", "Bruant auréole",
        "Bruant cendrillard", "Bruant des neiges", "Bruant des roseaux",
        "Bruant fou", "Bruant jaune", "Bruant lapon", "Bruant masqué",
        "Bruant mélanocéphale", "Bruant nain", "Bruant ortolan", "Bruant proyer",
        "Bruant roux", "Bruant rustique", "Bruant zizi",
        "Busard cendré", "Busard des roseaux", "Busard pâle", "Busard Saint-Martin",
        "Buse féroce", "Buse pattue", "Buse variable", "Butor étoilé",
        "Caille des blés",
        "Canard à front blanc", "Canard chipeau", "Canard colvert", "Canard mandarin",
        "Canard noir", "Canard pilet", "Canard siffleur", "Canard souchet",
        "Cassenoix moucheté", "Chardonneret élégant",
        "Chevalier à pattes jaunes", "Chevalier aboyeur", "Chevalier arlequin",
        "Chevalier bargette", "Chevalier criard", "Chevalier culblanc",
        "Chevalier de Sibérie", "Chevalier gambette", "Chevalier grivelé",
        "Chevalier guignette", "Chevalier stagnatile", "Chevalier sylvain",
        "Chevêche d'Athéna", "Chevêchette d'Europe",
        "Chocard à bec jaune", "Choucas des tours",
        "Chouette de Tengmalm", "Chouette épervière", "Chouette hulotte",
        "Cigogne blanche", "Cigogne noire", "Cincle plongeur",
        "Circaète Jean-le-blanc", "Cisticole des joncs",
        "Cochevis de Thékla", "Cochevis huppé",
        "Combattant varié", "Corbeau freux",
        "Cormoran huppé", "Cormoran pygmée",
        "Corneille mantelée", "Corneille noire",
        "Coucou geai", "Coucou gris",
        "Courlis à bec grêle", "Courlis cendré", "Courlis corlieu",
        "Courvite isabelle", "Crabier chevelu", "Crave à bec rouge",
        "Cygne chanteur", "Cygne de Bewick", "Cygne noir", "Cygne tuberculé",
        "Durbec des sapins", "Échasse blanche", "Effraie des clochers",
        "Eider à duvet", "Élanion blanc", "Engoulevent d'Europe", "Épervier d'Europe",
        "Érismature rousse", "Étourneau roselin", "Étourneau sansonnet", "Étourneau unicolore",
        "Faisan de Colchide", "Faucon concolore", "Faucon crécerelle", "Faucon crécerellette",
        "Faucon d'Éléonore", "Faucon émerillon", "Faucon gerfaut",
        "Faucon hobereau", "Faucon kobez", "Faucon lanier", "Faucon pèlerin", "Faucon sacre",
        "Fauvette à lunettes", "Fauvette à tête noire", "Fauvette babillarde",
        "Fauvette des jardins", "Fauvette épervière", "Fauvette grisette",
        "Fauvette mélanocéphale", "Fauvette naine", "Fauvette orphée",
        "Fauvette passerinette", "Fauvette pitchou", "Fauvette sarde",
        "Flamant rose", "Fou de Bassan", "Foulque macroule",
        "Fuligule à bec cerclé", "Fuligule milouin", "Fuligule milouinan",
        "Fuligule morillon", "Fuligule nyroca", "Fulmar boréal",
        "Gallinule poule-d'eau", "Garrot à œil d'or",
        "Geai des chênes", "Gélinotte des bois",
        "Gobemouche à collier", "Gobemouche gris", "Gobemouche noir",
        "Goéland argenté", "Goéland bourgmestre", "Goéland brun", "Goéland cendré",
        "Goéland d'Audouin", "Goéland leucophée", "Goéland marin", "Goéland railleur",
        "Goglu des prés", "Gorgebleue à miroir",
        "Grand Corbeau", "Grand Cormoran", "Grand Gravelot", "Grand Labbe",
        "Grand Tétras", "Grand-duc d'Europe", "Grande Aigrette",
        "Grèbe à cou noir", "Grèbe castagneux", "Grèbe huppé", "Grèbe jougris",
        "Grimpereau des bois", "Grimpereau des jardins",
        "Grive draine", "Grive litorne", "Grive mauvis", "Grive musicienne",
        "Grosbec casse-noyaux", "Grue cendrée", "Guêpier d'Europe", "Guifette noire",
        "Guillemot de Troïl", "Gypaète barbu",
        "Harelde boréale", "Harfang des neiges",
        "Harle bièvre", "Harle huppé", "Harle piette",
        "Héron cendré", "Héron garde-bœufs", "Héron pourpré",
        "Hibou des marais", "Hibou moyen-duc",
        "Hirondelle de fenêtre", "Hirondelle de rivage", "Hirondelle de rochers",
        "Hirondelle rousseline", "Hirondelle rustique",
        "Huîtrier pie", "Huppe fasciée", "Hypolaïs ictérine", "Hypolaïs polyglotte",
        "Ibis falcinelle", "Jaseur boréal", "Lagopède alpin",
        "Linotte mélodieuse", "Locustelle fasciée", "Locustelle fluviatile",
        "Locustelle luscinioïde", "Locustelle tachetée", "Loriot d'Europe",
        "Macareux moine", "Martin-pêcheur d'Europe",
        "Martinet à ventre blanc", "Martinet des maisons", "Martinet noir", "Martinet pâle",
        "Mergule nain", "Merle à plastron", "Merle noir",
        "Mésange azurée", "Mésange bleue", "Mésange boréale",
        "Mésange charbonnière", "Mésange huppée", "Mésange noire", "Mésange nonnette",
        "Milan noir", "Milan royal",
        "Moineau cisalpin", "Moineau domestique", "Moineau espagnol",
        "Moineau friquet", "Moineau soulcie",
        "Monticole bleu", "Monticole de roche",
        "Mouette mélanocéphale", "Mouette pygmée", "Mouette rieuse", "Mouette tridactyle",
        "Nette rousse", "Niverolle alpine", "Œdicnème criard",
        "Oie à bec court", "Oie cendrée", "Oie naine", "Oie rieuse",
        "Oriole de Baltimore", "Orite à longue queue", "Ouette d'Égypte",
        "Outarde barbue", "Outarde canepetière", "Panure à moustaches",
        "Pélican blanc", "Perdrix bartavelle", "Perdrix grise", "Perdrix rouge",
        "Perruche à collier", "Petit Gravelot", "Petit-duc scops",
        "Phalarope à bec étroit", "Phalarope à bec large",
        "Phragmite aquatique", "Phragmite des joncs",
        "Pic à dos blanc", "Pic cendré", "Pic épeiche", "Pic épeichette",
        "Pic mar", "Pic noir", "Pic tridactyle", "Pic vert",
        "Pie bavarde", "Pie-grièche à tête rousse", "Pie-grièche écorcheur",
        "Pie-grièche grise", "Pie-grièche méridionale",
        "Pigeon biset", "Pigeon colombin", "Pigeon ramier",
        "Pingouin torda", "Pinson des arbres", "Pinson du Nord",
        "Pipit à gorge rousse", "Pipit des arbres", "Pipit farlouse",
        "Pipit maritime", "Pipit rousseline", "Pipit spioncelle",
        "Plongeon arctique", "Plongeon catmarin", "Plongeon imbrin",
        "Pluvier argenté", "Pluvier doré",
        "Pouillot de Bonelli", "Pouillot fitis", "Pouillot siffleur",
        "Pouillot véloce", "Pouillot verdâtre",
        "Pygargue à queue blanche", "Râle d'eau", "Râle des genêts",
        "Rémiz penduline", "Roitelet à triple bandeau", "Roitelet huppé",
        "Rollier d'Europe", "Rossignol philomèle",
        "Rougegorge familier", "Rougequeue à front blanc", "Rougequeue noir",
        "Rousserolle effarvatte", "Rousserolle turdoïde", "Rousserolle verderolle",
        "Sarcelle d'été", "Sarcelle d'hiver", "Sarcelle marbrée",
        "Serin cini", "Sittelle torchepot", "Sizerin flammé", "Spatule blanche",
        "Sterne arctique", "Sterne caspienne", "Sterne caugek",
        "Sterne hansel", "Sterne naine", "Sterne pierregarin",
        "Tadorne casarca", "Tadorne de Belon", "Talève sultane",
        "Tarier des prés", "Tarier pâtre", "Tarin des aulnes",
        "Tétras lyre", "Tichodrome échelette", "Torcol fourmilier",
        "Tournepierre à collier", "Tourterelle des bois", "Tourterelle turque",
        "Traquet motteux", "Traquet oreillard", "Traquet pie",
        "Troglodyte mignon", "Vanneau huppé", "Vautour fauve",
        "Vautour moine", "Vautour percnoptère",
        "Venturon montagnard", "Verdier d'Europe"
    )
}